[server]
maxUploadSize = 200
enableXsrfProtection = false
enableCORS = false
fileWatcherType = "none"

[client]
showSidebarNavigation = false

[ui]
hideTopBar = false

[browser]
gatherUsageStats = false
# Force redeploy Tue Dec 16 15:44:44 UTC 2025
