[server]
maxUploadSize = 200
enableXsrfProtection = false
enableCORS = false
fileWatcherType = "none"

[client]
showSidebarNavigation = true

[ui]
hideTopBar = false

[browser]
gatherUsageStats = false
# Force redeploy Tue Dec 17 10:15:00 UTC 2025
